In [1]:
import numpy as np

sudoku_board1 = [[4, 0, 0, 6, 0, 3],
                [0, 5, 3, 0, 0, 0],
                [0, 0, 0, 0, 3, 6],
                [0, 0, 5, 2, 4, 1],
                [0, 2, 4, 3, 6, 5],
                [0, 3, 0, 4, 1, 0]]

sudoku_board2 = [[0, 0, 0, 0, 0, 6],
                [5, 4, 0, 0, 0, 1],
                [0, 0, 3, 4, 0, 5],
                [1, 0, 0, 0, 0, 0],
                [0, 2, 0, 0, 0, 0],
                [4, 0, 0, 0, 6, 0]]

sudoku_board = [[3, 0, 6, 1, 0, 0, 0, 8, 0],
               [0, 0, 0, 2, 0, 0, 0, 0, 4],
               [0, 4, 0, 0, 8, 5, 9, 0, 0],
               [0, 8, 0, 0, 0, 0, 1, 5, 0],
               [0, 7, 0, 0, 2, 9, 0, 0, 0],
               [5, 0, 4, 0, 0, 0, 0, 9, 6],
               [0, 0, 8, 0, 0, 4, 0, 0, 0],
               [1, 0, 0, 3, 0, 0, 0, 2, 7],
               [0, 0, 0, 0, 6, 0, 5, 0, 0]]

sudoku_size = np.size(sudoku_board)

num_rows = int(sudoku_size**(0.5))
num_cols = int(sudoku_size**(0.5))
for i in range(num_rows):
    print(sudoku_board[i])

[3, 0, 6, 1, 0, 0, 0, 8, 0]
[0, 0, 0, 2, 0, 0, 0, 0, 4]
[0, 4, 0, 0, 8, 5, 9, 0, 0]
[0, 8, 0, 0, 0, 0, 1, 5, 0]
[0, 7, 0, 0, 2, 9, 0, 0, 0]
[5, 0, 4, 0, 0, 0, 0, 9, 6]
[0, 0, 8, 0, 0, 4, 0, 0, 0]
[1, 0, 0, 3, 0, 0, 0, 2, 7]
[0, 0, 0, 0, 6, 0, 5, 0, 0]


In [2]:
sudo = np.array(sudoku_board)
print(sudo)

[[3 0 6 1 0 0 0 8 0]
 [0 0 0 2 0 0 0 0 4]
 [0 4 0 0 8 5 9 0 0]
 [0 8 0 0 0 0 1 5 0]
 [0 7 0 0 2 9 0 0 0]
 [5 0 4 0 0 0 0 9 6]
 [0 0 8 0 0 4 0 0 0]
 [1 0 0 3 0 0 0 2 7]
 [0 0 0 0 6 0 5 0 0]]


In [9]:
for i in range(num_rows):
    for j in range(num_cols):
        if sudoku_board[i][j] == 0:
            sudoku_board[i][j] = [(k+1) for k in range(num_rows)]

In [10]:
def define_box_6x6(sudoku_board, i, j):
    if i == 0 or i == 2 or i == 4:
        i_start = i
    elif i == 1 or i == 3 or i == 5:
        i_start = i-1
    if j == 0 or j == 3:
        j_start = j
        j_end = j + 3
    elif j == 1 or j == 4:
        j_start = j-1
        j_end = j+2
    elif j == 2 or j == 5:
        j_start = j-2
        j_end = j+1
    box = sudoku_board[i_start][j_start:j_end] + sudoku_board[i_start+1][j_start:j_end]
    return box



In [11]:
def define_box_9x9(sudoku_board, i, j):
    if i == 0 or i == 3 or i == 6:
        i_start = i
    elif i == 1 or i == 4 or i == 7:
        i_start = i-1
    elif i == 2 or i == 5 or i == 8:
        i_start = i-2
    if j == 0 or j == 3 or j == 6:
        j_start = j
        j_end = j + 3
    elif j == 1 or j == 4 or j == 7:
        j_start = j-1
        j_end = j+2
    elif j == 2 or j == 5 or j == 8:
        j_start = j-2
        j_end = j+1   
    box = sudoku_board[i_start][j_start:j_end] + sudoku_board[i_start+1][j_start:j_end] + sudoku_board[i_start+2][j_start:j_end]
    return box

box = define_box_9x9(sudoku_board, 1, 2)
print(define_box_9x9(sudoku_board, 4, 7))

[1, 5, [1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9], 9, 6]


In [12]:
def sudoku_solver(sudoku_board, solved = False):
    did_advance = 0
    if solved == True:
        did_advance = 1
        print('Sudoku is solved! \n')
        return
    
    for i in range(num_rows):
        for j in range(num_rows):
            cell = sudoku_board[i][j]
            if type(cell) != int:
                if len(cell) == 1:
                    sudoku_board[i][j] = cell[0]
                    did_advance += 1
            cell = sudoku_board[i][j]
            if type(cell) != int:
                cell = sudoku_board[i][j]
                row = sudoku_board[i]
                for elem in row:
                    if type(elem) == int and elem in cell:
                        cell.remove(elem)
                        did_advance += 1
                col = [row[j] for row in sudoku_board]
                for elem in col:
                    if type(elem) == int and elem in cell:
                        cell.remove(elem)
                        did_advance += 1
                if num_rows == 6:
                    box = define_box_6x6(sudoku_board, i, j)
                elif num_rows == 9:
                    box = define_box_9x9(sudoku_board, i, j)
                for elem in box:
                    if type(elem) == int and elem in cell:
                        cell.remove(elem)
                        did_advance += 1
    if did_advance == 0:
        return False
    else:
        return True                   

In [13]:
def check_if_solved(sudoku_board):
    check = 0                    
    for i in range(num_rows):
        for j in range(num_rows):
            cell = sudoku_board[i][j]
            if type(cell) != int:
                    check += 1
                    
    if check == 0:
        return True
    else: 
        return False

In [14]:
solved = False
is_solvable = True
iters = 0

while solved == False and is_solvable == True:
    solved = check_if_solved(sudoku_board)
    is_solvable = sudoku_solver(sudoku_board, solved = solved)
    if solved == False:
        print(f'Iteration {iters+1}')
        print('\n')
        for i in range(num_rows):
            print(sudoku_board[i])
        print('\n')
    if is_solvable == False:
        print('Sudoku cannot be solved by this solver!')
        
    iters += 1
    

Iteration 1


[3, [2, 5, 9], 6, 1, [4, 7, 9], [7], [2, 7], 8, [2, 5]]
[[7, 8, 9], [1, 5, 9], [1, 5, 7, 9], 2, [3, 7, 9], [3, 6, 7], [3, 6, 7], [1, 3, 6, 7], 4]
[[2, 7], 4, [1, 2, 7], [6, 7], 8, 5, 9, [1, 3, 6, 7], [1, 2, 3]]
[[2, 6, 9], 8, [2, 3, 9], [4, 6, 7], [3, 4, 7], [3, 6, 7], 1, 5, [2, 3]]
[[6], 7, [1, 3], [4, 5, 6, 8], 2, 9, [3, 4, 8], [3, 4], [3, 8]]
[5, [1, 2, 3], 4, [7, 8], [1, 3, 7], [1, 3, 7, 8], [2, 3, 7, 8], 9, 6]
[[2, 6, 7, 9], [2, 3, 5, 6, 9], 8, [5, 7, 9], [1, 5, 7, 9], 4, [3, 6], [1, 3, 6], [1, 3, 9]]
[1, [5, 6, 9], [5, 9], 3, [5, 9], [8], [4, 6, 8], 2, 7]
[[2, 4, 7, 9], [2, 3, 9], [2, 3, 7, 9], [7, 8, 9], 6, [1, 2, 7, 8], 5, [1, 3, 4], [1, 3, 8, 9]]


Iteration 2


[3, [2, 5, 9], 6, 1, [4, 7, 9], 7, [2], 8, [2, 5]]
[[7, 8, 9], [1, 5, 9], [1, 5, 7, 9], 2, [3, 9], [3, 6], [3, 6, 7], [1, 3, 6, 7], 4]
[[2, 7], 4, [1, 2, 7], [6], 8, 5, 9, [1, 3, 6, 7], [1, 2, 3]]
[[2, 6, 9], 8, [2, 3, 9], [4, 6, 7], [3, 4, 7], [3, 6], 1, 5, [2, 3]]
[6, 7, [1, 3], [4, 5, 8], 2, 9, [3, 4, 

In [ ]:
#Got to 4